# Generated by Django 3.1.3 on 2020-11-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='feedback',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
