# Generated by Django 3.1.3 on 2020-11-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='responder_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
