# Generated by Django 3.1.3 on 2020-11-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201128_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='see_response',
        ),
    ]
